### ISSUE TITLE
api.figma -> rate limit exceeded

### ISSUE THREAD

**Issue by nkpm** [KlausSchaefers/figma-low-code#13]
Hi there,

after following the install steps and running the server I get a blank screen in the browser. In the network traffic i see a lot of requests to api.figma.com with the result status=429 err="rate limit exceeded".

Is there something wrong with my installation?

Thanks and best Nils

**Comment by KlausSchaefers** [comment]
Hi,

this can indeed happen. In particular in big prototypes with a lot of vector graphics that I need to download as PNGs. How big is your prototype?

**Comment by nkpm** [comment]
pretty big. what number do you need?

**Comment by KlausSchaefers** [comment]
Could you share it with me (Klaus.schaefers@gmail.com) so I can have a look?

**Comment by nkpm** [comment]
unfortunately not, it's a business project

**Comment by xetra11** [comment]
@nkpm Maybe you can tell a rough amount of vector graphics to reproduce

**Comment by KlausSchaefers** [comment]
Hi,

I can try to add some throttling. This will make however the loading painfully slow. You will have to use the download script to load the assets once. 

As an alternative, one could limit the import to certain pages. Would this work?

Klaus

**Comment by alenamm** [comment]
Hello Klaus, I am getting exactly the same issue. How can I limit the import to a page?
Thanks in advance,
Alena

**Comment by KlausSchaefers** [comment]
Hi,

if you update the plugin one can select the page

```vue
<template>
  <div class="home">
    <Figma :figma="figmaConfig" v-model="viewModel" page="Page 1"/>
  </div>
</template>
```

Also, for large request I spread the API requests. I hope this fixes the Rate limit issue.
