### ISSUE TITLE
open plugins error

### ISSUE THREAD

**Issue by gdunser** [KlausSchaefers/figma-low-code#14]
------- Clearing and silencing console.log from Figma -------
figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:489 TypeError: cannot read property 'a' of undefined
    at colorToString (PLUGIN_13_SOURCE:282)
    at <anonymous> (PLUGIN_13_SOURCE:256)
    at forEach (native)
    at getColorFromNode (PLUGIN_13_SOURCE:257)
    at getColorFromNode (PLUGIN_13_SOURCE:273)
    at getColorFromNode (PLUGIN_13_SOURCE:273)
    at getColorFromNode (PLUGIN_13_SOURCE:273)
    at getColorFromNode (PLUGIN_13_SOURCE:273)
    at getColorFromNode (PLUGIN_13_SOURCE:273)
    at getAllColors (PLUGIN_13_SOURCE:239)
    at getStyles (PLUGIN_13_SOURCE:226)
    at ./src/code.ts (PLUGIN_13_SOURCE:160)
    at call (native)
    at __webpack_require__ (PLUGIN_13_SOURCE:20)
    at <anonymous> (PLUGIN_13_SOURCE:84)
    at <anonymous> (PLUGIN_13_SOURCE:304)
    at call (native)
    at <eval> (PLUGIN_13_SOURCE:307)

evalCodeInternal @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:489
evalTopLevelCode @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:489
(anonymous) @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1021
setTimeout (async)
runResult @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1021
n.runPluginCodeInRuntime @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1021
async function (async)
n.runPluginCodeInRuntime @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1021
runPluginCodeInternal @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1022
(anonymous) @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1022
async function (async)
(anonymous) @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1022
runPluginCode @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1022
runInstalledPlugin @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1022
async function (async)
runInstalledPlugin @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1022
runPlugin @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1022
E @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1032
(anonymous) @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1032
B.onSelectItem @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:4239
(anonymous) @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:577
(anonymous) @ figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:574
(anonymous) @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
w @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
(anonymous) @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
T @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
P @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
S @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
N @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
Un @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
Dn @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
n.unstable_runWithPriority @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:29
sl @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
Do @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
(anonymous) @ vendor.8b173c656b125e1a481e433adeccb433.min.js.br:40
figma_app.5354c0d9ddbd1e2c47e72e6f99a2619f.min.js.br:1022 ------- Restoring console.log functionality in Figma --------

**Comment by KlausSchaefersAtWork** [comment]
I will have a look. Can you share the figma project with me klaus.schaefers@gmail.com?

**Comment by gdunser** [comment]
sorry, my english is ver poor.
the same file
open in chrome, start it ok
open in mac app, error

**Comment by KlausSchaefers** [comment]
You are talking about the Figma plugin, correct? Not the LowCode app itself? I updateded the plugin, hopefully the bug does not appear anymore. To reload you have to reload Figma.

https://www.figma.com/community/plugin/858477504263032980
