### ISSUE TITLE
Is there way how to deal with interactive things?

### ISSUE THREAD

**Issue by oysterlab** [KlausSchaefers/figma-low-code#16]
Hi! :)
I really interesting about figma low code. and I read this article (https://uxdesign.cc/figma-low-code-a-new-way-to-tackle-design-hand-offs-a72cb109a455?gi=e452f9c367d8). I was very agree that code generation fail in agile project if code generation couldn't keep the business code written before auto generated to solve this problem you guys proposed data-biding, method-binding in your figma-low-code plugin.  so You said that this solution keep the pre-written  business logic before generating.
 But in this point, I feel little bit confused how to deal with interactive things. for example, lets have suppose we got the generated code from some button in figma. If I edit the button to  react such an interactive animation when I push the button and again re-generates the button's code, could I still keep my interactive animation code?
I already saw the youtube 'Figma Low Code - Step by Step Tutorial' (https://www.youtube.com/watch?v=n8YvL_YvXRA). But I couldn't find how to deal with interactive animation stuff in this video. 
thanks!

**Comment by KlausSchaefers** [comment]
Hi,

the is no 'code generation' of UI code. The Figma design is instead rendered to HTML and CSS. This happens on the fly in the background. Think of the Figma preview player, just with the possibility to include your own code. In practice this means:

1) You have one main file, e.g. Home.vue. 

2) In this file your include the <Figma> renderer and point it to the Figma file.

3) You add the data model to the Home.vue and pass it to the rendered. Like this you can pass data around

4) You implement  the business methods in Home.vue. You can also add custom CSS for animations or so.

5) When you update the design, he <Figma> component will just render the new design. You do not have to change anything in Home.vue. The css animation will continue working.

Cheers,

Klaus

**Comment by KlausSchaefers** [comment]
Fimga-Low-Code does not yet support animations. You can add them with CSS later by hand, or you could use Quant-UX.com to create the prototype. Quant-UX animation are supported.
