### ISSUE TITLE
[Feature] Respect letter case text style

### ISSUE THREAD

**Issue by keresztg** [KlausSchaefers/figma-low-code#18]
Currently the letter case text style setting has no effect in the Full Mode app. See following image where it is located:
![image](https://user-images.githubusercontent.com/43315663/117063558-4badab00-ad25-11eb-8d75-348c8773d93a.png)

The downloaded JSON does not contain anything similar as well.

`"s10000": {
      "id": "s10000",
      "figmaId": "1:2",
      "pageName": "Page 1",
      "name": "H2 Text",
      "type": "Screen",
      "x": -264,
      "y": -228,
      "w": 37,
      "h": 14,
      "props": {},
      "children": [],
      "style": {
        "fontFamily": "Roboto",
        "borderBottomWidth": 0,
        "borderTopWidth": 0,
        "borderLeftWidth": 0,
        "borderRightWidth": 0,
        "backgroundColor": "rgba(0, 0, 0, 1)",
        "fontSize": 12,
        "fontWeight": 400,
        "lineHeight": 1,
        "letterSpacing": 0,
        "textAlign": "left",
        "verticalAlign": "top"
      }
    }`

Would it be possible to support these settings?

**Comment by KlausSchaefers** [comment]
Hi,

I think I added the textTransform support. Please update the vue-low-code to 1.0.7 in your package.json or via NPM

```
nom update cue-low-code
```

CSS does not support all text-transforms in Figma, only Upper, Lower and capitalize.

Cheers,

Klaus
![Luisa-cloud](https://user-images.githubusercontent.com/7108416/117072394-a993c000-ad30-11eb-8109-5462053b75c8.png)

**Comment by keresztg** [comment]
Hi!

You were right! With vue-low-code 1.0.7 this works fine.
Then probably the package.json in figma-low-code would be nice to be updated.
Closing this issue.

Thanks for the prompt response,
Gábor

**Comment by KlausSchaefers** [comment]
Thanks for verifying the fix so quickly.
