### ISSUE TITLE
Hope support Tailwind CSS 

### ISSUE THREAD

**Issue by steveyang331** [KlausSchaefers/figma-low-code#2]
First ,really thank you build this tool, it's really fit my workflow.
More focusing design first , when I'm coding, coding faster. 

And Hope support Tailwind CSS. 

I've seen support custom css, but I don't know how to add tailwind css into "figma-low-code".

Thanks.

**Comment by KlausSchaefers** [comment]
Hi, what do you mean exactly. The main idea is to hide all CSS, so I am not sure where Tailwind would fit in? For the formating or layout?

**Comment by ashishvrm** [comment]
I am lost on that requst, how tailwind fits in this effort? Do an npm on your own project and you will get it. 

Btw, kudos to @KlausSchaefers ... thanks for building it. I did a small test project with figma and rest api to test the possibilities, But What you are doing is creative and helpful.
