### ISSUE TITLE
Open source the figma plugin

### ISSUE THREAD

**Issue by sondh0127** [KlausSchaefers/figma-low-code#26]
It would be great if the Figma plugin was also open-sourced:
https://www.figma.com/community/plugin/858477504263032980/Figma-Low-Code

**Comment by KlausSchaefers** [comment]
I will think about this. What are you missing?

**Comment by fahad-islam** [comment]
while using custom components we need to add more parameters so please

**Comment by KlausSchaefers** [comment]
Ok, take a look here https://github.com/KlausSchaefers/figma-low-code-plugin
