### ISSUE TITLE
Screen has fixed width

### ISSUE THREAD

**Issue by kokosro** [KlausSchaefers/figma-low-code#35]
Hi Klaus,

I'm trying out the plugin which seems to be the most awesome thing ever.
Input fields and buttons work as expected, but the Scene is fixed size and shows up as fixed width / height and doesn't stretch the full browser viewport.
Is there any special setting in figma for this or anything i can do to make a screen show up as full width/height in browser and not the fixed scene size as set in figma ?
Are there any limitation of the plugin that we have to be aware of so that we can build the design accordingly ?

Thank you

**Comment by KlausSchaefers** [comment]
Hi,

> I'm trying out the plugin which seems to be the most awesome thing ever.

Thanks!!!!

Normally screens / artboards should have always 100% of width. But all elements inside should have a fixed width unless the sides are pinned. I tried to explain this in here:

https://luisa.cloud/help/responsive_figma_layouts.html

You can also share your design with me, and I have a look. Best just drop the .fig file here.

**Comment by kokosro** [comment]
this is the design file
https://www.figma.com/file/2jJtwMuaNqdLo91YBIUWkV

using luisa-vue3-starter to test and this is how it is rendered in browser
![image](https://user-images.githubusercontent.com/995639/169668313-ce8814ba-d7f2-4a42-afdd-1bcd38386183.png)

**Comment by KlausSchaefers** [comment]
Hi,

I took a look at the file. I noticed the following things:

1) The "EmailBlock" element was set to "Input". This causes some strange nesting issues. Also the "Next" element is an input. This might happen copy copy pasting elements.

2)The text and email block was not correctly centred. Luisa currently ignores the center constraints. This is something I will fix soon. A quick workaround is to set the constraint to "left-right".

3) The EmailBlock had the Background as a child, although the background is bigger. This causes also some issues. It is best to have the nesting most similar to HTML. So parent elements should be larger than child elements.

4) The background needs to be constrained to left and right and top and down. There was a little bug regarding this. You need to install the latest version.

```
npm install luisa-vue@2.0.20
```

```
npm install luisa-vue@3.0.20
```


![image](https://user-images.githubusercontent.com/7108416/169708592-bd675c17-4c1c-4ebb-9de7-18333506039f.png)


The fixed version of the design is here:

https://www.figma.com/file/IaT7dtnwfvT8PEF6L9R2d2/Bug_EmailRegistration1?node-id=0%3A3

You get in general the best results with Auto-Layouts.

Does this solve your issue?

**Comment by kokosro** [comment]
Thank you, this has worked and it does stretch to 100% width. 
One question though, how can i make the background to also stretch to 100vh as now it one goes to the height set in figma ?
I've added 
```css
.BackgroundImage {
  height: 100vh;
}
```
in code and it does solve the issue, just wondering if there is a way to do it directly from figma.

**Comment by KlausSchaefers** [comment]
Hi,

I believe for now this is the best workaround. I have to see how I can add this to Luisa.

Cheers,

Klaus

**Comment by kokosro** [comment]
Thank you
