### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'min')

### ISSUE THREAD

**Issue by Code-Case** [KlausSchaefers/figma-low-code#39]
Hello,

Ive created a simple figma file to test the responsivness from figma-low-code: https://www.figma.com/file/owrluppOzpQweDmLkkml8M/Responsive-Test

1. created a page called: Desktop, as in your example video: https://www.youtube.com/watch?v=VIJiMAXUB-g
2. added my access and file id to the Home.vue
3. setup your plugin and checked Desktop and entered 1000 as minWidth 
4. downloaded the figma stuff
5. open up local host and get the error in my console:

`vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'min')"

found in

---> Luisa`

What did I miss here?

Thanks!

**Comment by KlausSchaefers** [comment]
Yes, this is a bug. I can recreate it. Thanks for posting!

**Comment by Code-Case** [comment]
Thats would be nice, I like the Idea to go low-code, thanks!

If I remove the reponsive config in home.vue I get the desktop View with the options from the low-code-plugin but I need tablet and mobile too.

best regards

**Comment by KlausSchaefers** [comment]
Hi, I think I found the bug. Could you try and update to the latest Luisa-vue package?

**Comment by Code-Case** [comment]
Hi, do you have an updated package.json, Ive updated the luisa package but get now the following error, I think I need to update more packages like vue and so on?

![figma-low-code-error](https://user-images.githubusercontent.com/1180305/190918118-bd65a9ee-89fb-40a2-b1a6-a5f5ff9e1cf4.jpg)

best regards

**Comment by KlausSchaefers** [comment]
Hm, I cannot reproduce the error. Did you start a fresh project and added Luisa or did you clone the start project? Can you share the package.js with me?

**Comment by KlausSchaefers** [comment]
Hi, I just updated all dependencies in the starter to the latest version offered by VUE CLI. Could you try to clone the starter?

https://github.com/KlausSchaefers/luisa-vue3-starter

**Comment by Code-Case** [comment]
> Hm, I cannot reproduce the error. Did you start a fresh project and added Luisa or did you clone the start project? Can you share the package.js with me?

Ive tryed to upgrade this repo here.

> Hi, I just updated all dependencies in the starter to the latest version offered by VUE CLI. Could you try to clone the starter?
> 
> https://github.com/KlausSchaefers/luisa-vue3-starter

Thanks for this, Ive used the starter and run npm install but then I cant use the npm run download:
![figma-low-code-error](https://user-images.githubusercontent.com/1180305/190981824-0abbd31c-cb56-4a44-8927-6eee8494788d.jpg)

EDIT: Ive added:     "luisa-util": "^1.0.9" to my package json and now it works :)
But: Ive added 3 pages for 3 devices types but I get only the dekstop page? 

Here is my test repo so you can check all: https://github.com/Code-Case/luisa-vue3-test

**Comment by KlausSchaefers** [comment]
Hi, if you resize the the browser window, Luisa should switch the right page. It's still the same Figma file?

**Comment by Code-Case** [comment]
> Hi, if you resize the the browser window, Luisa should switch the right page. It's still the same Figma file?

Yes its the same figma file, on resize I get only the Desktop Page and smaller breakpoints are blank.

best regards

**Comment by KlausSchaefers** [comment]
Hi,

for me this works:

```vue
<template>
  <Luisa :design="design" :config="config" v-model="viewModel"/>
</template>
<script>


export default {
  name: 'Home',
  data: function() {
    return {
      viewModel: {
        name:'',
        result: ''
      },
      config: {
        responsive: [
          { page: "Desktop", types: ["desktop"] },
          { page: "Mobile", types: ["tablet", "mobile"] },
        ]
      },
      design: {
        figmaFile:"owrluppOzpQweDmLkkml8M",
        figmaAccessKey: "....",
      },
    }
  },
  components: {
  },
  methods: {
  }
}
</script>
```

can you try it as well?

**Comment by Code-Case** [comment]
Wich pages did you import? 
Ive imported Desktop,Tablet,Mobile with npm run download, maybe that makes a difference?
I still get only my Desktop Page:

[luisa-vue3-starter.webm](https://user-images.githubusercontent.com/1180305/191337443-04bd0045-3fea-4328-8e6a-502d9fdb7134.webm)

**Comment by KlausSchaefers** [comment]
Could you try with the live loading?

**Comment by Code-Case** [comment]
Thank you so much for your time, now it works, I think it was because of the slow figma Api.
Nice plugin I will develop it a bit further for cases like using bootstrap for vue and so on.

best regards

**Comment by KlausSchaefers** [comment]
Hi,

thanks for the update! Yes the Figma API is at times very slow, in particular the PNG export might take some time. If you need more help or want to discuss your approach, just let me know!
