### ISSUE TITLE
Publish as an NPM package

### ISSUE THREAD

**Issue by sushant-j** [KlausSchaefers/figma-low-code#4]
Would be great to have it as an NPM package

**Comment by xetra11** [comment]
@sushant-j as far as I understand it's `vue-low-code` as a package which has `Figma` that you can use.
```import { Figma } from `vue-low-code`

**Comment by KlausSchaefers** [comment]
Hi,

xetra11 is right. Figma-Low-Code is just a thin wrapper on top of Vue-Low-Code. Take a look here https://www.npmjs.com/package/vue-low-code

**Comment by xetra11** [comment]
I might suggest to rename the thing to figma-vue-low-code then somewhat. Because maybe React developers might look at this and be somewhat confused

**Comment by Overdrivr** [comment]
@KlausSchaefers Awesome idea. Does it mean we can use the npm package `vue-low-code` with Full Mode with Figma ? Readme seems to say otherwise.

**Comment by KlausSchaefers** [comment]
Yes
