### ISSUE TITLE
How to setup Figma low code in a running vue project

### ISSUE THREAD

**Issue by xetra11** [KlausSchaefers/figma-low-code#8]
Hey there!
I am super excited to use this plugin. However I am struggling a bit how to install the `vue-low-code` library right now. In the tutorial video you show us how to use it in a single vue component file. The problem is that I don't wanna do a `Vue.use(Figma)` in every component, right?

So can you describe how I can make the Figma object available throughout the whole Vue project the same as plugins like Vuetify work? I kinda expected to see the guide how to add it in the `main.ts/js` file of my Vue project but could not find any documentation explaining that.

If this is actually a trivial question please excuse me. I am using Vue.js for a couple of month now and still not have the full grasp of the ecosystem and configuration yet.

**Comment by KlausSchaefers** [comment]
Hi,

you are right. You could also register the LowCode component in the main.js file. It should look like:

```
import Vue from 'vue'
import App from './App.vue'
import './registerServiceWorker'
import router from './router'

import Figma from 'vue-low-code'
Vue.use(Figma);

Vue.config.productionTip = false

new Vue({
  router,
  render: h => h(App)
}).$mount('#app')
```
