### ISSUE TITLE
Figma plugin does not work with certain Figma projects

### ISSUE THREAD

**Issue by xetra11** [KlausSchaefers/figma-low-code#9]
I created a fresh new figma project with a fresh user. I installed Figma plugin and it worked like a charm.

However when installing the low code plugin on a already existing Figma project (just a month old) the plugin does not work.
I clicked on every element I could find to see if it only works for certain types. Unfortunately the popup never opened. I clicked `Plugins > Figma-Low-Code`. Nothing happens.

Any idea why this is happening?

**Comment by elvacijunior** [comment]
Have you tried setting a 'prototype' on figma? It solved for me in a specific project. But in another one, I can't change thee home page to the desired frame also...and I don't know how to work with responsiveness on the plugin.

I wish we had an example project in Vue & Figma to learn from.

**Comment by xetra11** [comment]
@elvacijunior 
We are still figuring things out. The plugin is fresh so I kinda think it's our job to figure out problems :D

**Comment by elvacijunior** [comment]
I'd like to help wherever is possible, looks like a really awesome plugin and would be life-changing for a lot of companies and people :)

**Comment by KlausSchaefers** [comment]
Hi,

can you share the project with me: Klaus.schaefers@gmail.com? Maybe there is some bug during startup that makes the startup fail. I have to debug that.

**Comment by xetra11** [comment]
Sent you an invite. Thanks for your attention!

**Comment by KlausSchaefers** [comment]
Here is an example:

https://github.com/KlausSchaefers/figma-low-code-todo

The Figma file of the example is here:

https://www.figma.com/community/file/887084011990415230

**Comment by elvacijunior** [comment]
Thanks!!

**Comment by KlausSchaefers** [comment]
Hi,

I can't see the shared project in Figma...

**Comment by xetra11** [comment]
@KlausSchaefers I wrote you via Email

**Comment by KlausSchaefers** [comment]
Nope, didn't receive any thing. klaus.schaefers@gmail.com

**Comment by KlausSchaefers** [comment]
Version 3 should have fixed the bug!

https://www.figma.com/community/plugin/858477504263032980/Figma-Low-Code 

I guess after restarting Figma you should have the fix. Can you verify???

**Comment by xetra11** [comment]
Yes does work now! Thanks!

**Comment by KlausSchaefers** [comment]
Top! Thanks for the help!
